[package]
name = "logs-evaluation"
version = "0.1.0"
authors = ["Michael Watzko <michael.watzko@it-designers.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"